apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.rollupName }}-conductor-env
  namespace: astria-dev-cluster
data:
  home_dir: "/home/conductor"
  executor_host_grpc_port: "{{ .Values.ports.executionGRPC }}"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.rollupName }}-conductor-scripts
  namespace: astria-dev-cluster
data:
  start-conductor.sh: |
    {{- .Files.Get "files/scripts/start-conductor.sh" | nindent 4 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.rollupName }}-conductor-keys
  namespace: astria-dev-cluster
data:
  libp2p.key: |
    {{- .Files.Get "files/keys/libp2p.key" | nindent 4 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.rollupName }}-geth-env
  namespace: astria-dev-cluster
data:
  home_dir: "/home/geth"
  COMETBFT_RPC_ENDPOINT: "http://sequencer-service:26657"
  executor_host_http_port: "{{ .Values.ports.jsonRPC }}"
  executor_host_grpc_port: "{{ .Values.ports.executionGRPC }}"
  executor_host_ws_port: "{{ .Values.ports.wsRPC }}"
  sequencer_host_grpc_port: "9100"
  genesis_alloc_address: "{{ .Values.genesisAllocAddress }}"
  evm_chain_id: "{{ .Values.evmChainId }}"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.rollupName }}-executor-scripts
  namespace: astria-dev-cluster
data:
  geth-genesis.json: |
    {{- tpl (.Files.Get "files/genesis/geth-genesis.json") $ | nindent 4 }}
  init-geth.sh: |
    {{- .Files.Get "files/scripts/init-geth.sh" | nindent 4 }}
  start-geth.sh: |
    {{- .Files.Get "files/scripts/start-geth.sh" | nindent 4 }}
---
