kind: Service
apiVersion: v1
metadata:
  name: {{ .Values.rollupName }}-evm-service
  namespace: astria-dev-cluster
spec:
  selector:
    app: astria-dev-cluster
  ports:
    - name: json-rpc-svc
      port: {{ .Values.ports.jsonRPC }}
      targetPort: json-rpc
    - name: ws-rpc-svc
      port: {{ .Values.ports.wsRPC }}
      targetPort: ws-rpc
    - name: gossipnet-svc
      port: {{ .Values.ports.gossipnet }}
      targetPort: gossipnet
---
kind: Service
apiVersion: v1
metadata:
  name: {{ .Values.rollupName }}-faucet-service
  namespace: astria-dev-cluster
spec:
  selector:
    app: astria-dev-cluster
  ports:
    - name: faucet
      port: {{ .Values.ports.faucet }}
      targetPort: faucet
