# Default values for celestia-local.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

storage:
  enabled: true
  local: false
  entities:
    celestiaSharedStorage:
      size: "5Gi"
      persistentVolumeName: "celestia-shared-storage"
