kind: Service
apiVersion: v1
metadata:
  name: sequencer-service
  namespace: astria-dev-cluster
spec:
  selector:
    app: astria-dev-cluster
  ports:
    - name: cometbft-rpc
      port: {{ .Values.ports.cometBFTRPC }}
      targetPort: cometbft-rpc
    - name: gossipnet
      port: {{ .Values.ports.gossipnet }}
      targetPort: gossipnet
