kind: Service
apiVersion: v1
metadata:
  name: celestia-service
  namespace: astria-dev-cluster
spec:
  selector:
    app: astria-dev-cluster
  ports:
    - name: bridge-rest
      port: 26659
      targetPort: bridge-rest
    - name: bridge-jsonrpc
      port: 26658
      targetPort: bridge-jsonrpc
    - name: token-svc
      port: 5353
      targetPort: token-svc
