{{- if .Values.ingress.enabled -}}
{{- $ingressApiIsStable := eq (include "sequencer.ingress.isStable" .) "true" -}}
{{- $ingressSupportsIngressClassName := eq (include "sequencer.ingress.supportsIngressClassName" .) "true" -}}
{{- $ingressSupportsPathType := eq (include "sequencer.ingress.supportsPathType" .) "true" -}}
{{- $servicePort := tpl .Values.ingress.service.port . -}}
{{- $serviceName := tpl .Values.ingress.service.name . -}}
{{- $ingressPath := .Values.ingress.path -}}
{{- $ingressPathType := .Values.ingress.pathType -}}
{{- $extraPaths := tpl .Values.ingress.extraPaths . -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sequencer-faucet-ingress
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- with .Values.ingress.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- range $key, $value := . }}
    {{ $key }}: {{ tpl $value $ | quote }}
    {{- end }}
  {{- end }}
spec:
  {{- if and $ingressSupportsIngressClassName .Values.ingress.ingressClassName }}
  ingressClassName: {{ .Values.ingress.ingressClassName }}
  {{- end -}}
  {{- with .Values.ingress.defaultBackend }}
  defaultBackend:
    {{- tpl (toYaml .) $ | nindent 4 }}
  {{- end }}
  rules:
    {{- if .Values.ingress.hosts  }}
  {{- range .Values.ingress.hosts }}
    - host: {{ tpl . $ }}
      http:
        paths:
          {{- with $extraPaths }}
          {{- toYaml . | nindent 10 }}
          {{- end }}
          - path: {{ $ingressPath }}
            {{- if $ingressSupportsPathType }}
            pathType: {{ $ingressPathType }}
            {{- end }}
            backend:
              {{- if $ingressApiIsStable }}
              service:
                name: {{ tpl $serviceName }}
                port:
                  name: {{ $servicePort }}
              {{- else }}
              serviceName: {{ $serviceName }}
              servicePort: {{ $servicePort }}
              {{- end }}
  {{- end }}
  {{- with .Values.ingress.tls }}
  tls:
    {{- tpl (toYaml .) $ | nindent 4 }}
  {{- end }}
  {{- else }}
    - host: sequencer-faucet.localdev.me
      http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: sequencer-faucet-service
                port:
                  name: seq-faucet-svc
  {{- end -}}
{{- end }}
