{{- $label := include "celestiaNode.baseLabel" . }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $label }}-files-env
  namespace: {{ .Values.global.namespace }}
data:
  config.toml: |
  {{- tpl (.Files.Get "files/config.toml") $ | nindent 4 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $label }}-scripts-env
  namespace: {{ .Values.global.namespace }}
data:
  {{- (.Files.Glob "files/scripts/*").AsConfig | nindent 2 }}
---
{{- if eq .Values.config.network "custom" }}
{{- $customInfo := .Values.config.customInfo | required "customInfo is required for custom network" }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $label }}-env
  namespace: {{ .Values.global.namespace }}
data:
  CELESTIA_CUSTOM: {{ .Values.config.chainId }}:{{ $customInfo }}
{{- end }}
