{{- $label := include "baseLabel" . }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $label }}-files-env
  namespace: {{ .Values.namespace }}
data:
  config.toml: |
  {{- tpl (.Files.Get "files/config.toml") $ | nindent 4 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $label }}-scripts-env
  namespace: {{ .Values.namespace }}
data:
  {{- (.Files.Glob "files/scripts/*").AsConfig | nindent 2 }}
---
