apiVersion: v1
kind: Service
metadata:
  name: celestia-service
  namespace: astria-dev-cluster
spec:
  selector:
    app: astria-dev-cluster
  ports:
    - name: bridge-rest
      port: {{ .Values.ports.bridgeHTTP }}
      targetPort: bridge-rest
    - name: bridge-jsonrpc
      port: {{ .Values.ports.bridgeRPC }}
      targetPort: bridge-jsonrpc
    - name: token-svc
      port: {{ .Values.ports.celestiaTokenService }}
      targetPort: token-svc
