apiVersion: v1
kind: ConfigMap
metadata:
  name: metro-env
  namespace: astria-dev-cluster
data:
  coins: "1000000000000000utick"
  validator_stake: "5000000000utick"
  chainid: "private"
  keyring_backend: "test"
  validator_key_name: "validator"
  # evm address corresponds to private key:
  # da6ed55cb2894ac2c9c10209c09de8e8b9d109b910338d5bf3d747a7e1fc9eb9
  evm_address: "0x966e6f22781EF6a6A82BBB4DB3df8E225DfD9488"
  home_dir: "/home/metro"
  sequencer_host_port: "1318"
  sequencer_host_grpc_port: "9100"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: relayer-env
  namespace: astria-dev-cluster
data:
  home_dir: "/home/relayer"
---
