apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: astria-dev-cluster
resources:
- config-maps.yml
- deployment.yml
- service.yml
configMapGenerator:
- name: metro-scripts
  namespace: astria-dev-cluster
  files:
  - scripts/configure-metro.sh
  - scripts/init-metro.sh
  - scripts/start-metro.sh
