kind: Service
apiVersion: v1
metadata:
  name: sequencer-service
  namespace: astria-dev-cluster
spec:
  selector:
    app: astria-dev-cluster
  ports:
    - name: sequencer-svc
      port: 1318
      targetPort: sequencer-svc
    - name: transaction-svc
      port: 9100
      targetPort: transaction-svc
    - name: gossipnet
      port: 33900
      targetPort: gossipnet
