apiVersion: v1
kind: ConfigMap
metadata:
  name: conductor-env
  namespace: astria-dev-cluster
data:
  home_dir: "/home/conductor"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: geth-env
  namespace: astria-dev-cluster
data:
  executor_local_account: "0xb0E31D878F49Ec0403A25944d6B1aE1bf05D17E1"
  home_dir: "/home/geth"
  executor_host_http_port: "8545"
  executor_host_grpc_port: "50051"
  sequencer_host_grpc_port: "9100"
---
