{{- if and .Values.sequencer .Values.sequencer.secretProviderClass }}
---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: sequencerPrivateKey
spec:
{{ toYaml .Values.sequencer.secretProviderClass | indent 2 }}
{{- end }}
