# Default name for the rollup chain
rollupName: astria
# Default address where funds get allocated on genesis
genesisAllocAddress: "0xaC21B97d35Bf75A7dAb16f35b111a50e78A72F30"
# Default private key, must correspond with above address
privateKey: "8b3a7999072c9c9314c084044fe705db11714c6c4ed7cddb64da18ea270dd203"
# Default chain id
evmChainId: "astria"
# Default network id
evmNetworkId: 912559

# Default service ports
ports:
  jsonRPC: 8545
  wsRPC: 8546
  executionGRPC: 50051
  gossipnet: 2451
  faucet: 8080
  blockscout: 4000
