kind: Service
apiVersion: v1
metadata:
  name: sequencer-service
  namespace: astria-dev-cluster
spec:
  selector:
    app: astria-dev-cluster
  ports:
    - name: cometbft-rpc
      port: 26657
      targetPort: cometbft-rpc
    - name: gossipnet
      port: 33900
      targetPort: gossipnet
