apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.config.moniker }}-cometbft-config
  namespace: {{ .Values.global.namespace }}
data:
  genesis.json: |
    {{- tpl (.Files.Get "files/cometbft/config/genesis.json") $ | nindent 4 }}
  node_key.json: |
    {{- tpl (.Files.Get "files/cometbft/config/node_key.json") $ | nindent 4 }}
  priv_validator_key.json: |
    {{- tpl (.Files.Get "files/cometbft/config/priv_validator_key.json") $ | nindent 4 }}
  config.toml: |
    {{- tpl (.Files.Get "files/cometbft/config/config.toml") $ | nindent 4 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.config.moniker }}-cometbft-data
  namespace: {{ .Values.global.namespace }}
data:
  priv_validator_state.json: |
    {{- .Files.Get "files/cometbft/data/priv_validator_state.json" | nindent 4 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.config.moniker }}-cometbft-env
  namespace: {{ .Values.global.namespace }}
data:
  COMET_BFT_RPC_PORT: "{{ .Values.ports.cometBFTRPC }}"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.config.moniker }}-sequencer-env
  namespace: {{ .Values.global.namespace }}
data:
  ASTRIA_SEQUENCER_LOG: "astria_sequencer=debug"
  ASTRIA_SEQUENCER_LISTEN_ADDR: "127.0.0.1:{{ .Values.ports.sequencerABCI }}"
  ASTRIA_SEQUENCER_DB_FILEPATH: "/sequencer/penumbra.db"
  ASTRIA_SEQUENCER_ENABLE_MINT: "false"
  # Socket address for gRPC server
  ASTRIA_SEQUENCER_GRPC_ADDR: "127.0.0.1:{{ .Values.ports.sequencerGRPC }}"
---
