apiVersion: apps/v1
kind: Deployment
metadata:
  name: sequencer
  labels:
    app: {{ .Values.config.moniker }}-sequencer
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.config.moniker }}-sequencer
  template:
    metadata:
      annotations:
        cni.projectcalico.org/ipAddrs: '[ "{{ .Values.config.calicoIP }}" ]'
      name: astria-sequencer
      labels:
        app: {{ .Values.config.moniker }}-sequencer
    spec:
      initContainers:
        - command: [ "/bin/sh", "-c" ]
          args:
            - cp -LR /data/ /cometbft/data && cp -LR /config /cometbft/config && chmod -R 0777 /cometbft
          name: config-cometbft
          image: "ghcr.io/tomwright/dasel:alpine"
          volumeMounts:
            - mountPath: /config/
              name: cometbft-config-volume
            - mountPath: /data/
              name: cometbft-data-volume
            - mountPath: /cometbft
              name: sequencer-shared-storage-vol
              subPath: cometbft
      containers:
        - name: sequencer
          image: "{{ .Values.images.sequencer }}"
          command: [ "/usr/local/bin/astria-sequencer" ]
          stdin: {{ .Values.config.useTTY }}
          tty: {{ .Values.config.useTTY }}
          envFrom:
            - configMapRef:
                name: {{ .Values.config.moniker }}-sequencer-env
          volumeMounts:
            - mountPath: /sequencer
              name: sequencer-shared-storage-vol
              subPath: sequencer
          ports:
            - containerPort: {{ .Values.ports.sequencerABCI }}
              name: sequencer-abci
        - name: cometbft
          command: [ "cometbft", "start" ]
          args:
          - "--home"
          - "/cometbft"
          image: "{{ .Values.images.cometBFT }}"
          envFrom:
            - configMapRef:
                name: {{ .Values.config.moniker }}-cometbft-env
          volumeMounts:
            - mountPath: /cometbft
              name: sequencer-shared-storage-vol
              subPath: cometbft
          ports:
            - containerPort: {{ .Values.ports.cometBFTP2P }}
              name: cometbft-p2p
            - containerPort: {{ .Values.ports.cometBFTRPC }}
              name: cometbft-rpc
        {{- if .Values.config.relayer.enabled }}
        - name: sequencer-relayer
          image: "{{ .Values.images.sequencerRelayer }}"
          command: [ "/scripts/start-relayer.sh" ]
          stdin: {{ .Values.config.useTTY }}
          tty: {{ .Values.config.useTTY }}
          envFrom:
            - configMapRef:
                name: {{ .Values.config.moniker }}-relayer-env
          volumeMounts:
            - mountPath: /home/relayer
              name: sequencer-shared-storage-vol
              subPath: relayer
            - mountPath: /cometbft
              name: sequencer-shared-storage-vol
              subPath: cometbft
              readOnly: true
            - mountPath: /scripts/
              name: relayer-scripts-volume
        {{- end }}
      volumes:
        - name: cometbft-config-volume
          configMap:
            name: {{ .Values.config.moniker }}-cometbft-config
            defaultMode: 0700
        - name: cometbft-data-volume
          configMap:
            name: {{ .Values.config.moniker }}-cometbft-data
            defaultMode: 0700
        {{- if .Values.config.relayer.enabled }}
        - name: relayer-scripts-volume
          configMap:
            name: {{ .Values.config.moniker }}-relayer-scripts
            defaultMode: 0500
        {{- end }}
        - name: sequencer-shared-storage-vol
          {{- if .Values.storage.enabled }}
          persistentVolumeClaim:
            claimName: {{ .Values.config.moniker }}-sequencer-shared-storage-pvc
          {{- else }}
          emptyDir: {}
          {{- end }}
