apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: astria-dev-cluster-ingress
  namespace: astria-dev-cluster
spec:
  rules:
  - http:
      paths:
        - path: "/"
          pathType: Prefix
          backend:
            service:
              name: astria-dev-cluster-service
              port:
                number: 8545
---
