kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: astria-dev-cluster
networking:
  disableDefaultCNI: true # disable kindnet
  podSubnet: 192.168.0.0/16
nodes:
- role: control-plane
  image: kindest/node:v1.26.3@sha256:61b92f38dff6ccc29969e7aa154d34e38b89443af1a2c14e6cfbd2df6419c66f
  extraMounts:
    - hostPath: /tmp/astria/celestia-data
      containerPath: /data/celestia-data
    - hostPath: /tmp/astria/rollup-data/executor
      containerPath: /data/rollup-data/executor
    - hostPath: /tmp/astria/rollup-data/blockscout/logs
      containerPath: /data/rollup-data/blockscout/logs
    - hostPath: /tmp/astria/rollup-data/blockscout/postgres
      containerPath: /data/rollup-data/blockscout/postgres
    - hostPath: /tmp/astria/rollup-data/blockscout/redis
      containerPath: /data/rollup-data/blockscout/redis
    - hostPath: /tmp/astria/sequencer-data
      containerPath: /data/sequencer-data
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"
  extraPortMappings:
  - containerPort: 80
    hostPort: 80
    protocol: TCP
  - containerPort: 443
    hostPort: 443
    protocol: TCP
