config:
  celestia:
     rpc: "http://celestia-service.astria-dev-cluster.svc.cluster.local:26658"
     token: "http://celestia-service.astria-dev-cluster.svc.cluster.local:5353"

celestia-node:
  enabled: false
