kind: Service
apiVersion: v1
metadata:
  name: celestia-service
  namespace: astria-dev-cluster
spec:
  selector:
    app: astria-dev-cluster
  ports:
    - name: node-svc
      port: 26659
      targetPort: node-svc
