{{- if .Values.config.rollup.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: geth-metrics
  labels:
    {{- include "rollup.labels" . | nindent 4 }}
    {{- with .Values.config.rollup.serviceMonitor.additionalLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  jobLabel: geth-metrics
  namespaceSelector:
    matchNames:
      - {{ .Values.global.namespace }}
  selector:
    matchLabels:
      app: {{ .Values.config.rollup.name }}-astria-dev-cluster
  endpoints:
    - port: {{ .Values.config.rollup.serviceMonitor.port }}
      path: /debug/metrics/prometheus
      {{- with .Values.config.rollup.serviceMonitor.interval }}
      interval: {{ . }}
      {{- end }}
      {{- with .Values.config.rollup.serviceMonitor.scrapeTimeout  }}
      scrapeTimeout: {{ . }}
      {{- end }}
{{- end }}
