{{/* We need to manually create a PersistentVolume when local. */}}
{{/* In prod, a PV will be created by the StorageClass' provisioner using dynamic provisioning feature.  */}}
{{- if and .Values.storage.enabled }}
  {{- range $key, $value := .Values.storage.entities }}
    {{- if $.Values.storage.local }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ $.Values.config.rollup.name }}-{{ $value.persistentVolumeName }}-pv
spec:
  capacity:
    storage: {{ $value.size }}
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: {{ $.Values.config.rollup.name }}-{{ $value.persistentVolumeName }}-local
  local:
    path: {{ $value.path }}
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - astria-dev-cluster-control-plane
                - astria-dev-cluster-worker
                - astria-dev-cluster-worker2
                - astria-dev-cluster-worker3
---
    {{- end }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ $.Values.config.rollup.name }}-{{ $value.persistentVolumeName }}-pvc-geth
  namespace: astria-dev-cluster
  labels:
    "app.kubernetes.io/name": "{{ $.Values.config.rollup.name }}-{{ $.Chart.Name }}"
    "app.kubernetes.io/managed-by": {{ $.Release.Service | quote }}
    "helm.sh/chart": {{ $.Chart.Name }}-{{ $.Chart.Version | replace "+" "_" }}
spec:
  {{- if $.Values.storage.local }}
  storageClassName: {{ $.Values.config.rollup.name }}-{{ $value.persistentVolumeName }}-local
  {{- end }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ $value.size }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ $.Values.config.rollup.name }}-{{ $value.persistentVolumeName }}-pvc-blockscout
  namespace: astria-dev-cluster
  labels:
    "app.kubernetes.io/name": {{ $.Values.config.rollup.name }}-{{ $.Chart.Name }}
    "app.kubernetes.io/managed-by": {{ $.Release.Service | quote }}
    "helm.sh/chart": {{ $.Chart.Name }}-{{ $.Chart.Version | replace "+" "_" }}
spec:
  {{- if $.Values.storage.local }}
  storageClassName: {{ $.Values.config.rollup.name }}-{{ $value.persistentVolumeName }}-local
  {{- end }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ $value.size }}
---
  {{- end }}
{{- end }}
